config/routes.rb
Rails.application.routes.draw do
  root to: 'participants#index'
  resources :participants do
    member do
    put "approve"
    end
  end
  devise_for :users
  #map.resources.participants
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/participant.rb
class Participant < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_one :participant, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/participants_controller.rb
class ParticipantsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_participant, only: %i[ show edit update destroy, approve ]
  before_action :check_participant, only: [:show, :index]
  before_action :check_owner, only: [:show, :update, :destroy, :edit]

  # GET /participants or /participants.json
  def index
    if current_user.admin?
    @participants = Participant.all    
    else
      redirect_to new_participant_url
    end
    
    
  end

  # GET /participants/1 or /participants/1.json
  def show
    
    
  end

  # GET /participants/new
  def new
    if current_user.participant.nil?
    @participant = Participant.new
    else
      redirect_to @current_user.participant
    end
  end

  # GET /participants/1/edit
  def edit
  end

  # POST /participants or /participants.json
  def create
    
    @participant = current_user.build_participant(participant_params)
    
    respond_to do |format|
      if @participant.save
        format.html { redirect_to @participant, notice: "Participant was successfully created." }
        format.json { render :show, status: :created, location: @participant }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @participant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /participants/1 or /participants/1.json
  def update
    respond_to do |format|
      if @participant.update(participant_params)
        format.html { redirect_to @participant, notice: "Participant was successfully updated." }
        format.json { render :show, status: :ok, location: @participant }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @participant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /participants/1 or /participants/1.json
  def destroy
    if current_user.admin?
      @participant.destroy
    respond_to do |format|
      format.html { redirect_to participants_url, notice: "Participant was successfully destroyed." }
      format.json { head :no_content }
      end
    end    
  end

  def approve
    
    if @participant.kyc_approved?
      @participant.update_attribute :kyc_approved, false if current_user.admin?
      redirect_to @participant
    else
      @participant.update_attribute(:kyc_approved, true) if current_user.admin?
      redirect_to @participant
    end
    
  end
  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_participant
      @participant = Participant.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def participant_params
      params.require(:participant).permit(:firstname, :familyname, :kyc_approved, :agreement, :privacy_agr, :eth_adress, :cont_amount, :eth_tx, :user_id)
    end


    def check_participant
      if current_user.participant.nil?
        redirect_to new_participant_url
      end
    end

    def check_owner
      if @participant.user != current_user && current_user.admin == false
        redirect_to current_user.participant
      end
    end

    
    

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/participants_helper.rb
module ParticipantsHelper
end

app/views/layouts/_header.html.erb
<div class="container">
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div>
    <img src="https://pbs.twimg.com/profile_images/1374807950439616514/Z89shBwK.jpg" width="50px" />
    </div>
    <a class="navbar-brand" href="/"> | DEXGAME Katılımcı bilgi formu</a>
    <%if user_signed_in?%>
    <%= button_to "Logout", destroy_user_session_path, method: :delete, class: "btn btn-danger"  %>    
    <%else%>
    <%= button_to "Login", new_user_session_path, class: "btn btn-primary" %>
    <%end%>
  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dexgame</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render partial: 'layouts/header' %>
  <div class="container">
  
  

    <div class="row">
    <div class="col align-self-center">
    <%= yield %>
    </div>    
  </div>
  </div>
  </body>
</html>

app/views/participants/_form.html.erb
<%= form_with(model: participant) do |f| %>
<% if participant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(participant.errors.count, "error") %> prohibited this participant from being saved:</h2>

      <ul>
        <% participant.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<div class="card">
  <div class="card-body">

    <div class="mb-3">
      <%= f.label :firstname, { class: "form-label"} %>
      <%= f.text_field :firstname, { class: "form-control", placeholder: "Adınız" } %>
    </div>

    <div class="mb-3">
      <%= f.label :familyname, { class: "form-label"} %>
      <%= f.text_field :familyname, { class: "form-control", placeholder: "Soyadınız" } %>
    </div>

        <div class="mb-3">
      <label class="checkbox-inline">
   <%= f.check_box :privacy_agr %>
   <%= f.label "Satış sözleşmesi onayı" %>
  </label>
  <label class="checkbox-inline">
   <%= f.check_box :agreement %>
   <%= f.label "Gizlilik sözleşmesi onayı" %>
  </label>
    </div>

    <div class="mb-3">
      <%= f.label :eth_adress, { class: "form-label"} %>
      <%= f.text_field :eth_adress, { class: "form-control", placeholder: "Ethereum cüzdan adresiniz" } %>
    </div>

    <div class="mb-3">
      <%= f.label :eth_tx, { class: "form-label"} %>
      <%= f.text_field :eth_tx, { class: "form-control", placeholder: "Etheresum işlem ID'si(TX ID)" } %>
    </div>

    <div class="mb-3">
      <%= f.label :cont_amount, { class: "form-label"} %>
      <%= f.number_field :cont_amount, { class: "form-control", placeholder: "Satın alma miktarı(USDT)" } %>
    </div>

    <%= f.submit "Submit", class: "btn btn-primary" %>

  </div>
</div>
<% end %>

app/views/participants/edit.html.erb
<h1>Editing Participant</h1>

<%= render 'form', participant: @participant %>

<%= link_to 'Show', @participant %> |
<%= link_to 'Back', participants_path %>

app/views/participants/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Participants</h1>

<table>
  <thead>
    <tr>
      <th>Firstname</th>
      <th>Familyname</th>
      <th>Kyc approved</th>
      <th>Agreement</th>
      <th>Privacy agr</th>
      <th>Eth adress</th>
      <th>Cont amount</th>
      <th>Eth tx</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @participants.each do |participant| %>
      <tr>
        <td><%= participant.firstname %></td>
        <td><%= participant.familyname %></td>
        <td><%= participant.kyc_approved %></td>
        <td><%= participant.agreement %></td>
        <td><%= participant.privacy_agr %></td>
        <td><%= participant.eth_adress %></td>
        <td><%= participant.cont_amount %></td>
        <td><%= participant.eth_tx %></td>
        <td><%= participant.user_id %></td>
        <td><%= link_to 'Show', participant, class: "btn btn-info" %></td>
        <td><%= link_to 'Edit', edit_participant_path(participant), class: "btn btn-primary" %></td>
        <td><%= link_to 'Destroy', participant, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %></td>
        <% if current_user.admin?%>
          <% if participant.kyc_approved?%>          
             <td><%= link_to 'Onayı kaldır', approve_participant_path(participant), class: "btn btn-warning", method: :put %></td>        
          <% else %>
            <td><%= link_to 'Onayla', approve_participant_path(participant), class: "btn btn-success", method: :put %></td>
          <% end %>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Participant', new_participant_path %>

app/views/participants/new.html.erb
<h1>New Participant</h1>

<%= render 'form', participant: @participant %>

<%= link_to 'Back', participants_path %>

app/views/participants/show.html.erb
<p id="notice"><%= notice %></p>

<h1> Katılımcı Bilgileri</h1>
<h3><%= @participant.firstname + " " + @participant.familyname %></h3>



<p>
  <strong>Kyc:</strong>
  <%if @participant.kyc_approved %>
  <p class="text-success">Onaylandı</p>
  <% else %>
  <p class="text-danger">Onaylanmadı</p>
  <% end %>
</p>

<p>
  <strong>Satış Sözleşmesi:</strong>
  <%if @participant.agreement %>
  <p class="text-success">İmzalandı</p>
  <% else %>
  <p class="text-danger">İmzalanmadı</p>
  <% end %>
</p>


<p>
  <strong>Gizlilik Sözleşmesi</strong>
  
  <%if @participant.privacy_agr %>
  <p class="text-success">İmzalandı</p>
  <% else %>
  <p class="text-danger">İmzalanmadı</p>
  <% end %>
</p>

<p>
  <strong>Eth adress:</strong>
  <%= @participant.eth_adress %>
</p>

<p>
  <strong>Cont amount:</strong>
  <%= @participant.cont_amount %>
</p>

<p>
  <strong>Eth tx:</strong>
  <%= @participant.eth_tx %>
</p>

<p>
  <strong>User ID:</strong>
  <%= @participant.user_id %>
</p>

<%= link_to 'Edit', edit_participant_path(@participant), class: "btn btn-primary" %> |
<%= link_to 'Back', participants_path, class: "btn btn-default" %>
<% if current_user.admin?%>
          <% if @participant.kyc_approved?%>          
             <td><%= link_to 'Onayı kaldır', approve_participant_path(@participant), class: "btn btn-warning", method: :put %></td>        
          <% else %>
            <td><%= link_to 'Onayla', approve_participant_path(@participant), class: "btn btn-success", method: :put %></td>
          <% end %>
        <% end %>